### ISSUE TITLE
Acknowledge 2018's security standards

### ISSUE THREAD

**Issue by Eagle3386** [fnxweb/urllink#11]
Given that Firefox, Chrome and probably several other browsers discourage accessing non-HTTPS URLs nowadays (especially since Let's Encrypt offers SSL certificates for free), shouldn't we respect this where possible? Like in [line 463](https://github.com/fnxweb/urllink/blob/249279f50bd4807c2298767aa11ac8ff63ca480e/release/background.js#L463) of `background.js` - a possible section or an impossible one?

**Comment by fnxweb** [comment]
Firefox itself still defaults back to **http**;  I may make this an option, though.

**Comment by Eagle3386** [comment]
Looking forward to your implementation! 👍

**Comment by Eagle3386** [comment]
Any update on this? :smile:

**Comment by fnxweb** [comment]
I *did* start it, got distracted, and forgot all about it!

I'll set a reminder for next weekend…

**Comment by fnxweb** [comment]
Fixed by commit 310057932c05681576b8185f37e7b84c54b3d8d0

**Comment by Eagle3386** [comment]
@fnxweb may I ask for getting attributed as a contributor within the package's release notes or in the manifest, e. g. "and contributors (`<list of contributors>`)"?

**Comment by fnxweb** [comment]
Shit, should've thought of that. I'll put it in for the next drop.

You're in the changelog FWIW 😕

Soz.

**Comment by Eagle3386** [comment]
And now it's me who needs to apologize - my board and shiny new GPU just died, hence too many (RMA) mails to answer and your GitHub notification just fell through.. :disappointed:
Anyway, saw the mention in the changelog. Looking forward to the release note's entry. :wink:

Until then, I feel really honored for finally being mentioned within the extension which accompanies me throughout my whole Firefox-life. In fact, it was pretty much the first one I installed back in the days of Firefox 2.x - just after discovering that browser in general. So, thanks a lot for this special moment, Neil! :+1:

If Firefox for Android will *ever* support URL Link as an extension (install succeeded, but selected text doesn't offer its options), I'm sure I'll reach heaven.. :rofl:

**Comment by fnxweb** [comment]
Yeah, I just Android Firefox, and have been mulling how it might work. Things are a little … /different/ … for the version, though.

Soz about the PC 🙁

**Comment by Eagle3386** [comment]
Looking forward to such a version, though. :wink:

PC should ok again by the end of next week or at least the week after that - which is acceptable, because I'm flooded with work and I'm on holidays starting next Friday.. :grin:
