### ISSUE TITLE
Does  not work

### ISSUE THREAD

**Issue by MAGICCC** [fnxweb/urllink#13]
Hello,

I installed your addon in FF 68.0.2 (64-bit) using latest Windows, but seems it does not work. I selected a word, opened the context menu and tried to search the word on Wikipedia and Google, but no new tab/window will open

**Comment by fnxweb** [comment]
Hmm.  Seems OK on my _Linux_ 64-bit 68.0.2, so it's not an obvious breakage.

Can you please open both **&lt;F12&gt;[Console Window]** and **Tools/Web Developer/Browser Console** and see if any errors come up when you try to use one of the URL Link options?

Does the preferences window work?  If so, there's an _enable-debug_ option that should also print stuff (to the console window) when you use the extension (you'll need to _apply_ it, not just select it).

**Comment by MAGICCC** [comment]
~~Hm that's odd, on my desktop it does work now, but I installed it on my laptop now too, but there it does not work...~~

I want to use the addon at work where we have domain names in a table (tr/td) so I can open the serverinfo using context menu -> open in new tab
Seems the plugin does not work while selecting text in said table?

> Does the preferences window work? If so, there's an _enable-debug_ option that should also print stuff (to the console window) when you use the extension (you'll need to _apply_ it, not just select it).

Yes preferences window does work. I enabled the debug option for the second part below.


> Can you please open both **<F12>[Console Window]** and **Tools/Web Developer/Browser Console** and see if any errors come up when you try to use one of the URL Link options?

Console Window:
nothing

Tools/Web Developer/Browser Console:
`URL Link triggered with no selection background.js:487:17
    openLink moz-extension://e6aea3a3-d264-4dbb-a6d7-e0ecf1812c1b/background.js:487
    <anonymous> moz-extension://e6aea3a3-d264-4dbb-a6d7-e0ecf1812c1b/background.js:762`

I actually made a selection though

**Comment by fnxweb** [comment]
Strange. The selection text is passed to the extension by Firefox, so if I can't see it…

Maybe it's a bug triggered on a fresh install with newer versions of Firefox, I'll have a play when I get a chance.

**Comment by marcdraco** [comment]
Broken in 68.8.1 on Windows too. 

This is a desperately useful add-on because Windows 10 Mail clients seem to be sending links as plain text with the assumption that the receiver will convert them to links.

Is there any debugging info that I can send you to help?

**Comment by fnxweb** [comment]
I'll have a look later myself on a windows laptop with the latest version and get back to you.

**Comment by marcdraco** [comment]
Thanks Neil, this is a very important addon and it's a real bind that Mozilla keep breaking it!

**Comment by fnxweb** [comment]
Well, you won';t want to hear this, but I did a fresh install of TB 68.8.1 and URL Link in a Win10 VM and it worked fine :-/
You def., have the latest URL Link (3.4)?

If so, it's diag. time.  What're the symptoms?  No sign of menu changes when there's a selection (try with just a simple work selected to start with)?  Try toggling one of the show/hide submenu options to see if it's a broken combo (I ran with the defaults, all checkable options unticked, and “Show both...”).

Also, open both console and error windows (Tool/Dev Tools), clear their contents, then double-click a work and right-click, and see if any errors get logged.

Maybe watch the logs as well on a page refresh to see if it's logging an error registering the context callback?

**Comment by marcdraco** [comment]
This ****ing lockdown is screwing with my head. Will do as you suggest at the earliest opportunity... (*cough*) he says several months later.

**Comment by fnxweb** [comment]
You may wish to now try the WebExtensions rewrite (going through review ATM, or via file attachment on issue #17), assuming you haver a relatively recent TB (I've only tested it on 78 so far, will be testing on my Fedora-native 68 soon - if it works, I'll lower the compatibility tag appropriately).  Even if we get to the bottom of this, I probably won't be able to release copies of the legacy version any more.
