### ISSUE TITLE
Not working in Thunderbird 78.0

### ISSUE THREAD

**Issue by DavidBE-UK** [fnxweb/urllink#20]
I've updated to the new TB 78.0 released today, and urllink does not appear to be working (although it is showing as 'enabled' and not flagged as incompatible with 78.0. AS TB78 has gone full webextension only for add-ons, I'm wondering if I should try installing the Firefox version.

**Comment by fnxweb** [comment]
The Firefox version is highly unlikely to work, although I'm hoping to merge the two back together once TB has settled web extensions stuff. I'll have to look at the weekend to see what they've done *this* time.

**Comment by fnxweb** [comment]
Right, just a minor update:  the main Firefox WebExtensions re-write is now frustratingly close to working in Thunderbird, so what I'm going to do is focus my efforts on that;  I'll close this ticket to track it on that issue (#17).

**Comment by fnxweb** [comment]
I have pushed a beta release **3.5beta1** that works with TB 78.2 to the TB add-ons page.  I _hope_ it will be flagged as a beta and not be automatically rolled out, even though it seems mostly OK.  I don't think you will be able to access it until it's been reviewed, though, and it may fail that if they spot something (or I need another flag somewhere to really make it a beta).

**Please report any problems with it under issue #17!**

I'll try to attach a test XPI there in advance of the review (for the brave).
