### ISSUE TITLE
Enhancement  Url "name"

### ISSUE THREAD

**Issue by siomosp** [fnxweb/urllink#23]
Hi!
Thank you for the extension
It is possible to add a name for each url?
This is from a similar chrome extension
![name](https://user-images.githubusercontent.com/4071032/139449647-e1e2a603-58af-47ca-a9e4-fea8b0805bd9.jpg)
l?

**Comment by fnxweb** [comment]
If I understand correctly, then yes, just put a pipe character between a name and the URL:

`In Wi&kipedia|http://en.wikipedia.org/wiki/Special:Search?search=*&sourceid=mozilla-search`

**Comment by fnxweb** [comment]
(you can specify a menu shortcut key with **_&_** like above, but I've not yet put that functionality back in since the WebExtensions rewrite.)

**Comment by siomosp** [comment]
> If I understand correctly, then yes, just put a pipe character between a name and the URL:
> 
> `In Wi&kipedia|http://en.wikipedia.org/wiki/Special:Search?search=*&sourceid=mozilla-search`

It works, thank you!
