### ISSUE TITLE
Open in new Tab option in main context menu

### ISSUE THREAD

**Issue by McFergusson** [fnxweb/urllink#5]
In the old version of URLLink there was the possibility to have the "Open in new Tab" and "Open in new Window" options show up directly in the right click submenu.
Now i have to follow this path: "Right Click" -> **"URL Link"** -> "Open selection in new Tab" -> "(e.g.) In Google" instead of the much more comfortable "Right Click" -> "Open selection in new Tab" -> "(e.g.) In Google". I can't find any solution to recreate that behaviour.
Is it possible to bring that behaviour back?

**Comment by fnxweb** [comment]
Unfortunately not:  it is a “feature” of Firefox 57+'s WebExtensions that all add-ons that add to the context menu have their items put into a sub menu under the add-on's name 😕

**Comment by McFergusson** [comment]
I understand.
But maybe you could add the option to have the contents of the "Open selection in new Tab" submenu show up directly in the "URL Link" submenu. So the mouse path would look like "Right Click" -> "URL Link" -> "(e.g.) In Google" (and you have to adjust in the settings whether it should be opened in a new tab, in the same tab or in a new window). I would simply love to avoid to use an additional submenu, which, at least for me, makes using URL Link a bit more tedious since Quantum.

**Comment by fnxweb** [comment]
Yeah, that's do-able.  Won't be immediate, though :)

**Comment by fnxweb** [comment]
Just to re-iterate:   “_tough_” was a typo in the last comment (now fixed)!

**Comment by Eagle3386** [comment]
Please, Neil, I'm desperately & eagerly waiting for this "one sub-menu less" thing!

**Comment by fnxweb** [comment]
I'll see what I can do.

**Comment by fnxweb** [comment]
Don't hold your breath, Mozilla have changed their extension linter so I've a lot of things to clean up before I can put up a new release.

**Comment by Eagle3386** [comment]
Of course not - published my first extension (simple Google image search with better privacy, some tweaks and suggestions) a couple of weeks ago. Felt pretty tedious, actually..

But I've looked at the code already - thanks a lot, looking forward to get the update officially.
But maybe I'll feed my Firefox Nightly earlier.. 😎

**Comment by McFergusson** [comment]
Thanks a lot, Neil!
