### ISSUE TITLE
Prevent UTF-8 encoding of spaces within URL

### ISSUE THREAD

**Issue by Eagle3386** [fnxweb/urllink#7]
As shown in [background.js, line 474](https://github.com/fnxweb/urllink/blob/master/release/background.js#L474), `file:///` links get encoded under certain circumstances but keeps [several](https://github.com/fnxweb/urllink/blob/master/release/background.js#L427) characters from being encoded.

Recently, I had a Windows 7 machine which failed to access a Windows server 2012 UNC share, because whitespaces are encoded to `%20`. Without, i. e. replacing it with the original whitespaces again, it worked.

Hence, I'd like to ask for whitespaces being added to line 427.

**Comment by fnxweb** [comment]
Oh.  **file:///**  URLs shouldn't be going into that encoder _at all_ (ref. [the comment](https://github.com/fnxweb/urllink/blob/master/release/background.js#L474)).  _That's_ a bug — got an example?

**Comment by Eagle3386** [comment]
Sure, there you go:
Desired:
`file://///some-server/path/to.an/important folder/in some/deep/sub_directory/structure/`

Received:
`file://///some-server/path/to.an/important%20folder/in%20some/deep/sub_directory/structure/`

**Comment by fnxweb** [comment]
Ah, the ol' five-slash file: URL rears it's ugly head again ...

**Comment by Eagle3386** [comment]
Thanks so much again, Neil!

**Comment by fnxweb** [comment]
So long as it actually works! 😃

**Comment by Eagle3386** [comment]
Will test after vacation/upon add-on update.. 😉

**Comment by Eagle3386** [comment]
@fnxweb Unfortunately, it doesn't work. In fact, URL Link seems to make it even worse now:
`\\some-server\path\to.an\important folder\in some\deep\sub_directory\structure\`
gets turned into
`http://www.%5c%5csome-server%5cpath%5cto.an%5cimportant%20folder%5cin%20some%5cdeep%5csub_directory%5cstructure/`

Notice that not only spaces remain encoded, but slashes get encoded, too (though, the trailing slash isn't) and the wrong prefix is added (`http://www.`).

**Comment by fnxweb** [comment]
Sorry, not ignoring you, my mail for this address was broken and I didn't notice!

**Comment by fnxweb** [comment]
OK, that's interesting, that URL worked fine for me when I tested it.  I'll have another look.

**Comment by fnxweb** [comment]
OK, I'll be uploading 3.3.2 shortly, and that'll hopefully fix it.  AMO doesn't support betas any more, and it's PITA to self-sign add-ons, so we may have to go round the houses here a couple of times (unless you have the dev. version installed which accepts unsigned add-ons)!

A wholly different bug to the one I fixed earlier;  TBH, looking at the code, I can't figure out how it _ever_ worked!

**Comment by Eagle3386** [comment]
Regarding your comments:
1. Didn't thought so since your reply on AMO a couple of weeks (months?) ago. So, don't mention it. :smiley: 
2. Thanks for taking another look. I'm happily helping your investigation, just drop me a line.
3. I'm running Nightly here at home and Dev Edition at work - so, I just need a link to the XPI file.
Though, common sites (like Dropbox, GDrive, etc.) are blacklisted at work. Maybe GitHub is sufficient?

:rofl: @ your last sentence. I don't know either.. :wink:

**Comment by fnxweb** [comment]
Cool, if it's still bollox I'll attach an XPI to this.  Or you can always fetch it and add as a temporary plugin.

**Comment by Eagle3386** [comment]
Sorry for being late, I've not recovered from conjunctivitis and a deep-seated cold. Used the short brake from sleep and all, to improve a couple of minor bugs (see my PRs) and opened #11.

Regarding this one, I think I'll try the latter - less work and faster results for you. :smiley:

Additionally, running version 3.3.2, the abovementioned
`\\some-server\path\to.an\important folder\in some\deep\sub_directory\structure\`
now gets turned into
`file://///some-server/path/to.an/important folder/in some/deep/sub_directory/structure/`
hence neither wrong prefix nor falsely encoded slashes.

So, I'd call this finally fixed. Once again, thanks for your awesome work, Neil! :+1:

**Comment by fnxweb** [comment]
Cool.
I'll look at the other stuff over the weekend at some point.
